#!/usr/bin/php
<?php
// Envi2のディレクトリのパスを指定する。
$envi_dir = dirname(__FILE__).DIRECTORY_SEPARATOR.'libs/envi2/';

// 通常の設定はここまで。これ以下は必要がある場合のみ。

// Enviが管理するベースのディレクトリ
$base_dir = dirname(__FILE__).DIRECTORY_SEPARATOR;


require $envi_dir.'task/envi.php';

