#!/usr/bin/php
<?php
// Envi3のディレクトリのパスを指定する。
$envi_dir = dirname(__FILE__).DIRECTORY_SEPARATOR.'libs/envi3/';

// 通常の設定はここまで。これ以下は必要がある場合のみ。

// Enviが管理するベースのディレクトリ
$base_dir = dirname(__FILE__).DIRECTORY_SEPARATOR;
$current_work_dir = getcwd().DIRECTORY_SEPARATOR;

require $envi_dir.'task/envi.php';

