all:
  default_master:
    params:
      dsn: ""
      instance_pool: true
      connection_pool: false
      initialize_query: "set names utf8;"
  default_slave:
    params:
      dsn: ""
      instance_pool: true
      connection_pool: false
      initialize_query: "set names utf8;"
  default_stage:
    params:
      dsn: ""
      instance_pool: true
      connection_pool: false
      initialize_query: "set names utf8;"
