all:
  DBI:
    # ここをtrueにすると、リクエストごとにロードされ、オブジェクトが生成されます
    constant: true
    class:
      resource: "<?php echo ENVI_BASE_DIR.'vendor'.DIRECTORY_SEPARATOR;?>EnviDB.php"
      class_name: "DBInstance"
      singleton: true
    router:
      resource: "<?php echo dirname(__FILE__).DIRECTORY_SEPARATOR.'databases.yml';?>"